version: "3"

tasks:
  migrate:
    aliases:
      - migr
    desc: "Make migrations into storage"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations --migrations-table=migrations

  migrate_test:
    aliases:
      - migr_test
    desc: "Make migrations for tests"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test